### ISSUE TITLE
Kenny‘s Tasks

### ISSUE THREAD

**Issue by Yannahhh** [zmk5566/3D-Audio-Visualization-Sonification#1]
**Posted on Oct. 30th**
- Help generate the sounds with Data in Ableton Live

**Comment by zmk5566** [comment]
I will provide an alternative way of approaching it using freeware. I am thinking about using osc+puredata with airpod sensor data. 

Today I will provide research on the topic, will get back to you

**Comment by Yannahhh** [comment]
**Updated on 10.31st, 7:49am**:
- Kenny has helped developed the sounds with Data in Ableton Live.
